---
- name: Setup environment for ansible playbook test
  hosts: all
  become: yes
  tasks:
    - name: Create the user
      user:
        name: ansible
        shell: /bin/bash
    - name: Add user to the sudoers
      copy:
        dest: "/etc/sudoers.d/devops"
        content: "ansible ALL=(ALL) NOPASSWD: ALL"
    - name: Deploy SSH key
      authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
